import { test, expect } from '@playwright/test';

test('Login auto generated by codegen', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
 
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');

  await page.getByRole('button', { name: 'Login' }).click();

  await page.waitForTimeout(7000);

  await page.locator('span').filter({ hasText: 'Noidih Josh' }).click();

  await page.getByRole('menuitem', { name: 'Logout' }).click();
});